[package]
name = "async-h1"
version = "2.3.3"
license = "MIT OR Apache-2.0"
repository = "https://github.com/http-rs/async-h1"
documentation = "https://docs.rs/async-h1"
description = "Asynchronous HTTP 1.1 parser."
keywords = ["async", "http", "stream", "parser", "http1"]
categories = [
  "asynchronous",
  "parser-implementations",
  "web-programming",
  "web-programming::http-client",
  "web-programming::http-server"
]
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
readme = "README.md"
edition = "2018"
rust-version = "1.63"

[dependencies]
async-channel = "1.5.1"
async-dup = "1.2.2"
async-global-executor = "2.3.1"
async-io = "2.3.4"
futures-lite = "2.3.0"
http-types = { version = "2.9.0", default-features = false }
httparse = "1.3.4"
log = "0.4.11"
pin-project = "1.0.2"

[dev-dependencies]
async-std = { version = "1.13.0", features = ["attributes"] }
pretty_assertions = "1.4.0"
